/**
 * A code block.
 *
 * Highlighting must never delay reading, and must never drag a whole language bundle into the app:
 *   - the plain, correctly spaced source renders on the first paint, before shiki is even fetched;
 *   - shiki's core, the JavaScript regex engine and ONE grammar load in the background, on demand,
 *     the first time a block of that language appears. `shiki` (the full bundle) is never imported;
 *   - the theme is createCssVariablesTheme, so highlighted code inherits the page palette from
 *     index.css and follows light/dark without re-highlighting;
 *   - any failure leaves the plain source on screen. Unhighlighted code is readable; a blank is not.
 *
 * Registered languages are exactly the ones the curriculum uses.
 */
import type { HighlighterCore } from 'shiki/core';
import { useEffect, useRef, useState } from 'react';

const LOADERS = {
  java: () => import('shiki/langs/java.mjs'),
  python: () => import('shiki/langs/python.mjs'),
  javascript: () => import('shiki/langs/javascript.mjs'),
  typescript: () => import('shiki/langs/typescript.mjs'),
  bash: () => import('shiki/langs/bash.mjs'),
  sql: () => import('shiki/langs/sql.mjs'),
  yaml: () => import('shiki/langs/yaml.mjs'),
  json: () => import('shiki/langs/json.mjs'),
} as const;

type Registered = keyof typeof LOADERS;

const ALIASES: Record<string, Registered> = {
  java: 'java',
  py: 'python',
  python: 'python',
  js: 'javascript',
  jsx: 'javascript',
  javascript: 'javascript',
  mjs: 'javascript',
  ts: 'typescript',
  tsx: 'typescript',
  typescript: 'typescript',
  sh: 'bash',
  shell: 'bash',
  zsh: 'bash',
  console: 'bash',
  bash: 'bash',
  sql: 'sql',
  yml: 'yaml',
  yaml: 'yaml',
  json: 'json',
};

const THEME_NAME = 'itmc-tokens';

let corePromise: Promise<HighlighterCore> | undefined;
const loadedLangs = new Set<Registered>();

async function getHighlighter(): Promise<HighlighterCore> {
  corePromise ??= (async () => {
    const [{ createHighlighterCore, createCssVariablesTheme }, { createJavaScriptRegexEngine }] = await Promise.all([
      import('shiki/core'),
      import('shiki/engine/javascript'),
    ]);
    return createHighlighterCore({
      themes: [createCssVariablesTheme({ name: THEME_NAME, variablePrefix: '--shiki-', fontStyle: true })],
      langs: [],
      // Pure JS: no wasm payload, and `forgiving` degrades an unsupported pattern instead of throwing.
      engine: createJavaScriptRegexEngine({ forgiving: true }),
    });
  })();
  return corePromise;
}

async function highlight(code: string, lang: Registered): Promise<string> {
  const hl = await getHighlighter();
  if (!loadedLangs.has(lang)) {
    await hl.loadLanguage(LOADERS[lang]);
    loadedLangs.add(lang);
  }
  return hl.codeToHtml(code, { lang, theme: THEME_NAME });
}

export function resolveLang(lang: string | undefined): Registered | undefined {
  return lang ? ALIASES[lang.toLowerCase().trim()] : undefined;
}

export function CodeBlock({ code, lang, caption }: { code: string; lang?: string; caption?: string }) {
  const resolved = resolveLang(lang);
  const [html, setHtml] = useState<string | undefined>(undefined);
  const alive = useRef(true);

  useEffect(() => {
    alive.current = true;
    return () => {
      alive.current = false;
    };
  }, []);

  useEffect(() => {
    setHtml(undefined);
    if (!resolved) return;
    let cancelled = false;
    highlight(code, resolved)
      .then((out) => {
        if (!cancelled && alive.current) setHtml(out);
      })
      .catch(() => undefined);
    return () => {
      cancelled = true;
    };
  }, [code, resolved]);

  return (
    <figure className="my-5 border border-rule">
      {(lang || caption) && (
        <figcaption className="flex items-baseline justify-between gap-3 border-b border-rule bg-surface px-3 py-1.5">
          <span className="label">{caption ?? ''}</span>
          {lang ? <span className="label text-ink-3">{lang}</span> : null}
        </figcaption>
      )}
      <div className="code-surface">
        {html ? (
          // shiki output: HTML it generated by escaping the source, rendered with our token colours.
          <div dangerouslySetInnerHTML={{ __html: html }} />
        ) : (
          <pre>
            <code>{code}</code>
          </pre>
        )}
      </div>
    </figure>
  );
}
